--- 
jobs:
  terraform: 
    env: 
      ARM_CLIENT_ID: "${{secrets.ARM_CLIENT_ID}}"
      ARM_CLIENT_SECRET: "${{secrets.MYSUPERSECRETE}}"
      ARM_SUBSCRIPTION_ID: "${{secrets.MYSBSCRIPTIONID}}"
      ARM_TENANT_ID: "${{secrets.ARM_TENANT_ID}}"
    runs-on: ubuntu-latest
    steps: 
      ? "-name"
      : "Terraform Plan run terraform plan"
      ? "-uses"
      : actions/checkout@v2
name: "Terraform plan"
true: 
  push: 
    branches: 
      - FeatureBranch1

